export const db = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    title: "Senior Technology Advisor",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    linkedin: "https://linkedin.com/in/johndoe",
    bio: "John is a seasoned technology advisor with over 15 years of experience in software development and entrepreneurship.",
    mentorExpertises: [
      { title: "Software Development" },
      { title: "Product Strategy" },
      { title: "Tech Startups" },
    ],
    programCount: 12,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.8,
  },
  {
    id: 2,
    name: "Sarah Wilson",
    email: "john.doe@example.com",
    title: "Marketing & Growth Expert",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "Sarah specializes in growth marketing and has helped scale multiple startups to million-dollar revenues.",
    linkedin: "https://linkedin.com/in/sarahwilson",
    mentorExpertises: [
      { title: "Growth Marketing" },
      { title: "Digital Marketing" },
      { title: "Brand Strategy" },
    ],
    programCount: 8,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.9,
  },
  {
    id: 3,
    name: "Ahmed Hassan",
    email: "john.doe@example.com",
    title: "Investment & Finance Advisor",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "Ahmed brings extensive experience in venture capital and startup financing across the MENA region.",
    linkedin: "https://linkedin.com/in/ahmedhassan",
    mentorExpertises: [
      { title: "Venture Capital" },
      { title: "Financial Planning" },
      { title: "Investment Strategy" },
    ],
    programCount: 15,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.7,
  },
  {
    id: 4,
    name: "Maria Rodriguez",
    email: "john.doe@example.com",
    title: "UX/UI Design Lead",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "Maria is a creative design expert who has worked with Fortune 500 companies to create user-centric digital experiences.",
    linkedin: "https://linkedin.com/in/mariarodriguez",
    mentorExpertises: [
      { title: "UX Design" },
      { title: "UI Design" },
      { title: "Design Systems" },
      { title: "User Research" },
    ],
    programCount: 18,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.9,
  },
  {
    id: 5,
    name: "David Chen",
    email: "john.doe@example.com",
    title: "AI & Machine Learning Consultant",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "David specializes in AI implementation and has helped numerous startups integrate machine learning into their products.",
    linkedin: "https://linkedin.com/in/davidchen",
    mentorExpertises: [
      { title: "Artificial Intelligence" },
      { title: "Machine Learning" },
      { title: "Data Science" },
      { title: "Python" },
      { title: "TensorFlow" },
    ],
    programCount: 22,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.8,
  },
  {
    id: 6,
    name: "Fatima Al-Zahra",
    email: "john.doe@example.com",
    title: "Operations & Strategy Director",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "Fatima has led operations for multiple high-growth startups and specializes in scaling business processes.",
    linkedin: "https://linkedin.com/in/fatimaalzahra",
    mentorExpertises: [
      { title: "Operations Management" },
      { title: "Business Strategy" },
      { title: "Process Optimization" },
      { title: "Team Leadership" },
    ],
    programCount: 14,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.6,
  },
  {
    id: 7,
    name: "Michael Thompson",
    email: "john.doe@example.com",
    title: "Sales & Business Development Expert",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "Michael has built and led sales teams that generated over $100M in revenue across various industries.",
    linkedin: "https://linkedin.com/in/michaelthompson",
    mentorExpertises: [
      { title: "Sales Strategy" },
      { title: "Business Development" },
      { title: "Revenue Growth" },
      { title: "Client Relations" },
    ],
    programCount: 16,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.7,
  },
  {
    id: 8,
    name: "Priya Sharma",
    email: "john.doe@example.com",
    title: "Product Management Leader",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "Priya has managed product portfolios at tech giants and successfully launched products used by millions of users.",
    linkedin: "https://linkedin.com/in/priyasharma",
    mentorExpertises: [
      { title: "Product Management" },
      { title: "Product Strategy" },
      { title: "Agile Methodology" },
      { title: "User Analytics" },
      { title: "Market Research" },
    ],
    programCount: 20,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.9,
  },
  {
    id: 9,
    name: "Omar Khalil",
    email: "john.doe@example.com",
    title: "Cybersecurity & IT Infrastructure",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "Omar is a cybersecurity expert who has protected startups and enterprises from digital threats for over a decade.",
    linkedin: "https://linkedin.com/in/omarkhalil",
    mentorExpertises: [
      { title: "Cybersecurity" },
      { title: "Network Security" },
      { title: "Cloud Infrastructure" },
      { title: "Compliance" },
    ],
    programCount: 11,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.8,
  },
  {
    id: 10,
    name: "Lisa Chang",
    email: "john.doe@example.com",
    title: "HR & Talent Development Specialist",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "Lisa helps startups build strong company cultures and attract top talent in competitive markets.",
    linkedin: "https://linkedin.com/in/lisachang",
    mentorExpertises: [
      { title: "Human Resources" },
      { title: "Talent Acquisition" },
      { title: "Company Culture" },
      { title: "Performance Management" },
    ],
    programCount: 13,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.6,
  },
  {
    id: 11,
    name: "Carlos Mendoza",
    email: "john.doe@example.com",
    title: "E-commerce & Digital Transformation",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "Carlos has helped traditional businesses transition to digital platforms and optimize their e-commerce strategies.",
    linkedin: "https://linkedin.com/in/carlosmendoza",
    mentorExpertises: [
      { title: "E-commerce" },
      { title: "Digital Transformation" },
      { title: "Online Marketing" },
      { title: "Supply Chain" },
    ],
    programCount: 17,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.7,
  },
  {
    id: 12,
    name: "Dr. Aisha Okafor",
    email: "john.doe@example.com",
    title: "Healthcare Innovation Advisor",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "Dr. Aisha combines medical expertise with business acumen to guide healthcare startups through regulatory challenges.",
    linkedin: "https://linkedin.com/in/aishaokafor",
    mentorExpertises: [
      { title: "Healthcare Innovation" },
      { title: "Medical Technology" },
      { title: "Regulatory Compliance" },
      { title: "Digital Health" },
      { title: "Clinical Research" },
    ],
    programCount: 9,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.9,
  },
  {
    id: 13,
    name: "Robert Kim",
    email: "john.doe@example.com",
    title: "Blockchain & Fintech Strategist",
    image_url:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2",
    bio: "Robert is at the forefront of blockchain technology and has advised numerous fintech startups on cryptocurrency integration.",
    linkedin: "https://linkedin.com/in/robertkim",
    mentorExpertises: [
      { title: "Blockchain Technology" },
      { title: "Cryptocurrency" },
      { title: "Fintech" },
      { title: "Smart Contracts" },
      { title: "DeFi" },
    ],
    programCount: 12,
    programIds: ["1", "2"],
    role: "mentor",
    rating: 4.8,
  },
];
