import { ProjectType } from "@/types/projectTypes";

export const db: Array<ProjectType> = [
  {
    id: "1",
    title: "Project 1",
    progress: 75,
    status: "In Progress",
    description: "This is a description of Project 1.",
    programs: [
      { id: "p1", title: "Program 1" },
      { id: "p2", title: "Program 2" },
      { id: "p3", title: "Program 3" },
    ],
    programsCount: 3,
    teamMembers: [
      { id: "tm1", userName: "John Doe", role: "Project Manager" },
      { id: "tm2", userName: "Jane Smith", role: "Developer" },
      { id: "tm3", userName: "Michael Johnson", role: "Designer" },
      { id: "tm4", userName: "Sarah Williams", role: "Business Analyst" },
    ],
    startDate: "2021-01-01",
    endDate: "2021-01-01",
    budget: "$100,000",
  },
  {
    id: "2",
    title: "Project 2",
    progress: 50,
    status: "In Progress",
    description: "This is a description of Project 2.",
    programs: [
      { id: "p1", title: "Program 1" },
      { id: "p2", title: "Program 2" },
      { id: "p3", title: "Program 3" },
    ],
    programsCount: 2,
    teamMembers: [
      { id: "tm5", userName: "Robert Brown", role: "Project Manager" },
      { id: "tm6", userName: "Emily Davis", role: "Developer" },
      { id: "tm7", userName: "David Miller", role: "QA Engineer" },
    ],
    startDate: "2021-01-01",
    endDate: "2021-01-01",
    budget: "$50,000",
  },
  {
    id: "3",
    title: "Project 3",
    status: "In Progress",
    description: "This is a description of Project 3.",
    progress: 90,
    programs: [
      { id: "p1", title: "Program 1" },
      { id: "p2", title: "Program 2" },
      { id: "p3", title: "Program 3" },
    ],
    programsCount: 5,
    teamMembers: [
      { id: "tm8", userName: "Jennifer Wilson", role: "Product Owner" },
      { id: "tm9", userName: "Thomas Anderson", role: "Technical Lead" },
      { id: "tm10", userName: "Lisa Taylor", role: "UX Designer" },
      { id: "tm11", userName: "James Martinez", role: "Developer" },
      { id: "tm12", userName: "Patricia Garcia", role: "Developer" },
    ],
    startDate: "2021-01-01",
    endDate: "2021-01-01",
    budget: "$200,000",
  },
  {
    id: "4",
    title: "Project 4",
    status: "In Progress",
    description: "This is a description of Project 4.",
    progress: 30,
    programs: [
      { id: "p1", title: "Program 1" },
      { id: "p2", title: "Program 2" },
      { id: "p3", title: "Program 3" },
    ],
    programsCount: 3,
    teamMembers: [
      { id: "tm13", userName: "Charles Anderson", role: "Project Manager" },
      { id: "tm14", userName: "Jessica Lee", role: "Developer" },
      { id: "tm15", userName: "Daniel Harris", role: "QA Engineer" },
    ],
    startDate: "2021-01-01",
    endDate: "2021-01-01",
    budget: "$75,000",
  },
];
