// Startup data for the incubator platform

import { StartupType } from "@/types/startupTypes"

export const db: StartupType[] = [
  {
    id: "1",
    logo: "https://beta.growthlabs.app/191014/images/logo/VPY4AAeYmQA31sPm0HJTHJAYVakT3LVikqCU5wlb.png",
    name: "EcoTech Solutions",
    sector: "Renewable Energy",
    establishmentDate: "2022-05-15",
    state: "California",
    country: "United States",
    city: "San Francisco",
    founders: [
      { name: "Sarah Johnson", role: "CEO" },
      { name: "Michael Chen", role: "CTO" },
      { name: "Amara Patel", role: "COO" },
    ],
    sustainabilityGoals: [
      "Carbon Neutral by 2026",
      "Zero Waste Production",
      "100% Renewable Energy",
    ],
  },
  {
    id: "2",
    logo: "https://beta.growthlabs.app/191014/images/logo/startup-logos/greenfield.svg",
    name: "GreenField Agritech",
    sector: "Agriculture",
    establishmentDate: "2023-02-22",
    state: "Iowa",
    country: "United States",
    city: "Des Moines",
    founders: [
      { name: "Marcus Wilson", role: "CEO" },
      { name: "Priya Sharma", role: "CTO" },
    ],
    sustainabilityGoals: [
      "Reduce Water Usage by 40%",
      "Sustainable Farming Practices",
      "Farm-to-Table Supply Chain",
    ],
  },
  {
    id: "3",
    logo: "https://beta.growthlabs.app/191014/images/logo/startup-logos/meditech.svg",
    name: "MediTech Innovations",
    sector: "Healthcare",
    establishmentDate: "2021-11-10",
    state: "Massachusetts",
    country: "United States",
    city: "Boston",
    founders: [
      { name: "Elena Rodriguez", role: "CEO" },
      { name: "David Kim", role: "CTO" },
      { name: "Jessica Thompson", role: "CMO" },
    ],
    sustainabilityGoals: [
      "Affordable Healthcare Solutions",
      "Eco-friendly Medical Products",
      "Telemedicine for Rural Areas",
    ],
  },
  {
    id: "4",
    logo: "https://beta.growthlabs.app/191014/images/logo/startup-logos/finedge.svg",
    name: "FinEdge",
    sector: "Financial Technology",
    establishmentDate: "2023-01-05",
    state: "New York",
    country: "United States",
    city: "New York City",
    founders: [
      { name: "James Harrison", role: "CEO" },
      { name: "Olivia Chen", role: "CTO" },
      { name: "Robert Miller", role: "CFO" },
    ],
    sustainabilityGoals: [
      "Financial Inclusion",
      "Carbon-Neutral Operations",
      "Ethical Investment Portfolios",
    ],
  },
  {
    id: "5",
    logo: "https://beta.growthlabs.app/191014/images/logo/startup-logos/edureach.svg",
    name: "EduReach",
    sector: "Education Technology",
    establishmentDate: "2022-09-30",
    state: "Texas",
    country: "United States",
    city: "Austin",
    founders: [
      { name: "Lisa Wang", role: "CEO" },
      { name: "Andre Johnson", role: "CTO" },
      { name: "Maya Patel", role: "COO" },
    ],
    sustainabilityGoals: [
      "Digital Education for Underprivileged",
      "Reduce Paper Consumption",
      "Sustainable Learning Materials",
    ],
  },
  {
    id: "6",
    logo: "https://beta.growthlabs.app/191014/images/logo/startup-logos/urbanmobility.svg",
    name: "Urban Mobility",
    sector: "Transportation",
    establishmentDate: "2022-08-12",
    state: "Washington",
    country: "United States",
    city: "Seattle",
    founders: [
      { name: "Carlos Mendez", role: "CEO" },
      { name: "Aisha Williams", role: "CTO" },
    ],
    sustainabilityGoals: [
      "Zero-Emission Vehicles",
      "Reduce Urban Traffic by 30%",
      "Sustainable Urban Planning",
    ],
  },
  {
    id: "7",
    logo: "https://beta.growthlabs.app/191014/images/logo/startup-logos/cleanseas.svg",
    name: "CleanSeas",
    sector: "Environmental Conservation",
    establishmentDate: "2023-03-20",
    state: "Florida",
    country: "United States",
    city: "Miami",
    founders: [
      { name: "Emma Davis", role: "CEO" },
      { name: "Noah Lee", role: "CTO" },
      { name: "Sophia Martinez", role: "CSO" },
    ],
    sustainabilityGoals: [
      "Ocean Plastic Reduction",
      "Coral Reef Restoration",
      "Clean Water Technologies",
    ],
  },
  {
    id: "8",
    logo: "https://beta.growthlabs.app/191014/images/logo/startup-logos/aiethics.svg",
    name: "AI Ethics Lab",
    sector: "Artificial Intelligence",
    establishmentDate: "2022-06-05",
    state: "California",
    country: "United States",
    city: "Palo Alto",
    founders: [
      { name: "Jamal Washington", role: "CEO" },
      { name: "Leila Rahman", role: "CTO" },
      { name: "Thomas Brown", role: "Chief Ethics Officer" },
    ],
    sustainabilityGoals: [
      "Ethical AI Development",
      "Inclusive Technology",
      "Energy-Efficient Computing",
    ],
  },
  {
    id: "9",
    logo: "https://beta.growthlabs.app/191014/images/logo/startup-logos/foodcircle.svg",
    name: "FoodCircle",
    sector: "Food Technology",
    establishmentDate: "2023-04-10",
    state: "Oregon",
    country: "United States",
    city: "Portland",
    founders: [
      { name: "Hannah Kim", role: "CEO" },
      { name: "Daniel Garcia", role: "CTO" },
      { name: "Grace Liu", role: "CSO" },
    ],
    sustainabilityGoals: [
      "Reduce Food Waste by 50%",
      "Sustainable Packaging",
      "Local Food Ecosystems",
    ],
  },
]