import { SurveyType, QuestionType } from "@/types/surveyTypes";
import { OrgType } from "@/types/OrgTypes";
import { Program } from "@/types/mentorshipTypes";
import { StartupType } from "@/types/startupTypes";
import { Mentor } from "@/types/MentorTypes";

// Mock organizations
export const mockOrganizations: OrgType[] = [
  { name: "Tech Innovation Hub", id: "org-1" },
  { name: "Digital Transformation Center", id: "org-2" },
  { name: "Startup Accelerator", id: "org-3" },
  { name: "Business Development Lab", id: "org-4" },
  { name: "Innovation Network", id: "org-5" },
  { name: "Entrepreneurship Center", id: "org-6" },
  { name: "Research Institute", id: "org-7" },
  { name: "Industry Partnership", id: "org-8" },
];

// Mock programs
export const mockPrograms: Program[] = [
  {
    id: "prog-1",
    name: "AI Innovation Accelerator",
    description: "12-week intensive program focused on AI and machine learning startups",
    startDate: "2024-01-15T00:00:00Z",
    endDate: "2024-04-15T00:00:00Z",
    participantCount: 15,
    mentorCount: 8,
    isActive: true,
  },
  {
    id: "prog-2",
    name: "FinTech Bootcamp",
    description: "8-week program for financial technology startups",
    startDate: "2024-02-01T00:00:00Z",
    endDate: "2024-03-26T00:00:00Z",
    participantCount: 12,
    mentorCount: 6,
    isActive: true,
  },
  {
    id: "prog-3",
    name: "Sustainability Ventures",
    description: "16-week program for climate and sustainability focused startups",
    startDate: "2024-01-08T00:00:00Z",
    endDate: "2024-04-29T00:00:00Z",
    participantCount: 20,
    mentorCount: 12,
    isActive: true,
  },
  {
    id: "prog-4",
    name: "Healthcare Innovation Program",
    description: "10-week program for healthcare and medical technology startups",
    startDate: "2024-02-15T00:00:00Z",
    endDate: "2024-04-30T00:00:00Z",
    participantCount: 18,
    mentorCount: 10,
    isActive: true,
  },
  {
    id: "prog-5",
    name: "EdTech Accelerator",
    description: "12-week program focused on educational technology innovations",
    startDate: "2024-01-22T00:00:00Z",
    endDate: "2024-04-22T00:00:00Z",
    participantCount: 14,
    mentorCount: 7,
    isActive: true,
  },
  {
    id: "prog-6",
    name: "E-commerce Growth Program",
    description: "8-week intensive program for e-commerce and retail tech startups",
    startDate: "2024-03-01T00:00:00Z",
    endDate: "2024-04-26T00:00:00Z",
    participantCount: 16,
    mentorCount: 9,
    isActive: true,
  },
  {
    id: "prog-7",
    name: "Deep Tech Incubator",
    description: "20-week program for deep technology and research-based startups",
    startDate: "2024-01-01T00:00:00Z",
    endDate: "2024-05-20T00:00:00Z",
    participantCount: 8,
    mentorCount: 15,
    isActive: true,
  },
  {
    id: "prog-8",
    name: "Social Impact Accelerator",
    description: "14-week program for social enterprises and impact-driven startups",
    startDate: "2024-02-05T00:00:00Z",
    endDate: "2024-05-14T00:00:00Z",
    participantCount: 22,
    mentorCount: 11,
    isActive: true,
  },
];

// Mock startups
export const mockStartups: StartupType[] = [
  {
    id: "startup-1",
    logo: "/images/logos/startup1.png",
    name: "EcoTech Solutions",
    sector: "Environmental Technology",
    establishmentDate: "2023-03-15",
    state: "California",
    country: "USA",
    city: "San Francisco",
    founders: [
      { name: "Sarah Johnson", role: "CEO" },
      { name: "Michael Chen", role: "CTO" },
    ],
    sustainabilityGoals: ["Clean Energy", "Carbon Reduction"],
  },
  {
    id: "startup-2",
    logo: "/images/logos/startup2.png",
    name: "HealthAI Innovations",
    sector: "Healthcare Technology",
    establishmentDate: "2023-06-22",
    state: "New York",
    country: "USA",
    city: "New York",
    founders: [
      { name: "Dr. Emma Wilson", role: "CEO" },
      { name: "Alex Rodriguez", role: "COO" },
    ],
    sustainabilityGoals: ["Healthcare Access", "Medical Innovation"],
  },
  {
    id: "startup-3",
    logo: "/images/logos/startup3.png",
    name: "FinFlow Technologies",
    sector: "Financial Technology",
    establishmentDate: "2023-01-10",
    state: "Texas",
    country: "USA",
    city: "Austin",
    founders: [
      { name: "David Kim", role: "CEO" },
      { name: "Lisa Zhang", role: "CFO" },
    ],
    sustainabilityGoals: ["Financial Inclusion", "Digital Banking"],
  },
];

// Mock mentors
export const mockMentors: Mentor[] = [
  {
    id: 1,
    name: "Dr. Jennifer Adams",
    title: "Senior Technology Advisor",
    image_url: "/images/avatars/mentor1.jpg",
    bio: "20+ years in AI and machine learning, former Google AI researcher",
    linkedin: "https://linkedin.com/in/jennifer-adams",
    mentorExpertises: [
      { title: "Artificial Intelligence" },
      { title: "Machine Learning" },
      { title: "Product Strategy" },
    ],
    programCount: 3,
    rating: 4.9,
  },
  {
    id: 2,
    name: "Mark Thompson",
    title: "Venture Capital Partner",
    image_url: "/images/avatars/mentor2.jpg",
    bio: "Former startup founder, now helping early-stage companies scale",
    linkedin: "https://linkedin.com/in/mark-thompson",
    mentorExpertises: [
      { title: "Fundraising" },
      { title: "Business Development" },
      { title: "Go-to-Market Strategy" },
    ],
    programCount: 5,
    rating: 4.8,
  },
  {
    id: 3,
    name: "Dr. Priya Patel",
    title: "Healthcare Innovation Expert",
    image_url: "/images/avatars/mentor3.jpg",
    bio: "Former Chief Medical Officer at multiple healthcare startups",
    linkedin: "https://linkedin.com/in/priya-patel",
    mentorExpertises: [
      { title: "Healthcare Technology" },
      { title: "Regulatory Affairs" },
      { title: "Clinical Development" },
    ],
    programCount: 2,
    rating: 4.9,
  },
];

// Sample questions pool
export const sampleQuestions: QuestionType[] = [
  {
    id: "q1",
    text: "How would you rate your overall satisfaction with our service?",
    type: "star-rating",
    maxRating: 5,
    required: true,
  },
  {
    id: "q2",
    text: "Would you recommend our service to others?",
    type: "yes-no",
    required: true,
  },
  {
    id: "q3",
    text: "What improvements would you suggest for our product?",
    type: "question-answer",
    required: false,
  },
  {
    id: "q4",
    text: "How satisfied are you with the customer support?",
    type: "star-rating",
    maxRating: 5,
    required: true,
  },
  {
    id: "q5",
    text: "Did you find our onboarding process helpful?",
    type: "yes-no",
    required: false,
  },
  {
    id: "q6",
    text: "Please describe your experience with our platform",
    type: "question-answer",
    required: false,
  },
  {
    id: "q7",
    text: "Rate the user interface design",
    type: "star-rating",
    maxRating: 5,
    required: true,
  },
  {
    id: "q8",
    text: "Is the pricing fair for the value provided?",
    type: "yes-no",
    required: false,
  },
  {
    id: "q9",
    text: "How likely are you to continue using our service?",
    type: "star-rating",
    maxRating: 10,
    required: true,
  },
  {
    id: "q10",
    text: "What features would you like to see added in the future?",
    type: "question-answer",
    required: false,
  },
  {
    id: "q11",
    text: "Are you satisfied with the response time of our support team?",
    type: "yes-no",
    required: false,
  },
  {
    id: "q12",
    text: "Rate the quality of our documentation",
    type: "star-rating",
    maxRating: 5,
    required: false,
  },
];

// Mock surveys data
export const mockSurveys: SurveyType[] = [
  {
    id: "survey-1",
    title: "Customer Satisfaction Survey",
    organization: mockOrganizations[0],
    tags: ["customer-satisfaction", "feedback", "product"],
    questions: [sampleQuestions[0], sampleQuestions[1], sampleQuestions[3]],
    description: "A comprehensive survey to measure customer satisfaction levels and gather feedback for improvements.",
    status: "active",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
    totalResponses: 145,
    scope: "training",
    triggeredAfter: "session",
    engagementRate: 78.5,
    program: mockPrograms[0],
    startup: mockStartups[0],
    mentor: mockMentors[0],
  },
  {
    id: "survey-2",
    title: "Product Feedback Collection",
    organization: mockOrganizations[1],
    tags: ["product-feedback", "user-experience", "innovation"],
    questions: [sampleQuestions[2], sampleQuestions[6], sampleQuestions[9]],
    description: "Gathering insights about user experience and product improvement suggestions.",
    status: "draft",
    createdAt: "2024-02-01T09:15:00Z",
    updatedAt: "2024-02-05T16:45:00Z",
    totalResponses: 23,
    scope: "mentorship",
    triggeredAfter: "cycle completion",
    engagementRate: 65.2,
    program: mockPrograms[1],
    startup: mockStartups[1],
    mentor: mockMentors[1],
  },
  {
    id: "survey-3",
    title: "Employee Engagement Survey",
    organization: mockOrganizations[2],
    tags: ["employee-engagement", "workplace", "culture"],
    questions: [sampleQuestions[4], sampleQuestions[5], sampleQuestions[8]],
    description: "Understanding employee satisfaction and engagement levels within the organization.",
    status: "active",
    createdAt: "2024-01-25T11:30:00Z",
    updatedAt: "2024-02-10T12:00:00Z",
    totalResponses: 89,
    scope: "training",
    triggeredAfter: "session",
    engagementRate: 82.3,
    program: mockPrograms[2],
    startup: mockStartups[2],
    mentor: mockMentors[2],
  },
  {
    id: "survey-4",
    title: "Market Research Survey",
    organization: mockOrganizations[3],
    tags: ["market-research", "business-strategy", "analytics"],
    questions: [],
    description: "Comprehensive market analysis and consumer behavior study.",
    status: "inactive",
    createdAt: "2024-01-10T08:45:00Z",
    updatedAt: "2024-01-15T17:20:00Z",
    totalResponses: 0,
    scope: "mentorship",
    triggeredAfter: "cycle completion",
    engagementRate: 0,
    program: mockPrograms[0],
  },
  {
    id: "survey-5",
    title: "Training Program Evaluation",
    organization: mockOrganizations[4],
    tags: ["training", "education", "evaluation"],
    questions: [sampleQuestions[0], sampleQuestions[4], sampleQuestions[11]],
    description: "Evaluate the effectiveness of our training programs and identify areas for improvement.",
    status: "active",
    createdAt: "2024-02-05T14:20:00Z",
    updatedAt: "2024-02-12T09:15:00Z",
    totalResponses: 67,
    scope: "training",
    triggeredAfter: "session",
    engagementRate: 73.2,
    program: mockPrograms[1],
    startup: mockStartups[0],
    mentor: mockMentors[1],
  },
  {
    id: "survey-6",
    title: "Website Usability Study",
    organization: mockOrganizations[5],
    tags: ["usability", "website", "user-interface"],
    questions: [sampleQuestions[6], sampleQuestions[7], sampleQuestions[11]],
    description: "Assess the usability and user experience of our website.",
    status: "archived",
    createdAt: "2023-12-10T11:45:00Z",
    updatedAt: "2023-12-20T16:30:00Z",
    totalResponses: 234,
    scope: "training",
    triggeredAfter: "session",
    engagementRate: 91.5,
    program: mockPrograms[2],
    startup: mockStartups[1],
  },
  {
    id: "survey-7",
    title: "Service Quality Assessment",
    organization: mockOrganizations[6],
    tags: ["service-quality", "customer-support", "satisfaction"],
    questions: [sampleQuestions[0], sampleQuestions[3], sampleQuestions[10]],
    description: "Measure the quality of our customer service and support.",
    status: "draft",
    createdAt: "2024-02-15T08:30:00Z",
    updatedAt: "2024-02-15T08:30:00Z",
    totalResponses: 0,
    scope: "training",
    triggeredAfter: "session",
    engagementRate: 0,
    mentor: mockMentors[2],
  },
  {
    id: "survey-8",
    title: "Innovation Culture Survey",
    organization: mockOrganizations[7],
    tags: ["innovation", "culture", "organizational"],
    questions: [sampleQuestions[1], sampleQuestions[5], sampleQuestions[9]],
    description: "Assess the innovation culture and mindset within the organization.",
    status: "active",
    createdAt: "2024-01-30T13:15:00Z",
    updatedAt: "2024-02-08T10:45:00Z",
    totalResponses: 156,
    scope: "mentorship",
    triggeredAfter: "cycle completion",
    engagementRate: 87.9,
    program: mockPrograms[0],
    startup: mockStartups[2],
    mentor: mockMentors[0],
  },
];

export default {
  mockSurveys,
  sampleQuestions,
  mockOrganizations,
};
