
import { CourseType } from "@/types/CourseTypes"

// Fake DB for courses
export const db: CourseType[] = [
  {
    id: "course-001",
    image: "/images/cards/course-react-fundamentals.jpg",
    title: "Introduction to React Development",
    description: "Learn the fundamentals of React including components, state management, hooks, and modern development practices. Perfect for beginners looking to start their journey in frontend development.",
    tags: ["React", "JavaScript", "Frontend", "Web Development"],
    categories: ["Programming", "Web Development"],
    level: "Beginner",
    relatedQuizzes: 5,
    visibilityStatus: "Public",
    courseCode: "REACT-101-2024",
    enrolledStudents: 1247,
    duration: "8 weeks"
  },
  {
    id: "course-002",
    image: "/images/cards/course-advanced-javascript.jpg",
    title: "Advanced JavaScript Concepts",
    description: "Deep dive into JavaScript's advanced features including prototypal inheritance, closures, async patterns, and design patterns. Suitable for developers looking to enhance their JS knowledge.",
    tags: ["JavaScript", "ES6+", "Design Patterns", "Async"],
    categories: ["Programming", "Web Development"],
    level: "Advanced",
    relatedQuizzes: 8,
    visibilityStatus: "Public",
    courseCode: "JS-ADV-2024",
    enrolledStudents: 892,
    duration: "10 weeks"
  },
  {
    id: "course-003",
    image: "/images/cards/course-typescript.jpg",
    title: "TypeScript for Modern Applications",
    description: "Master TypeScript to build type-safe applications. Learn interfaces, generics, utility types, and best practices for integrating with React, Node, and other frameworks.",
    tags: ["TypeScript", "JavaScript", "Static Typing"],
    categories: ["Programming", "Web Development"],
    level: "Intermediate",
    relatedQuizzes: 6,
    visibilityStatus: "Public",
    courseCode: "TS-201-2024",
    enrolledStudents: 723,
    duration: "6 weeks"
  },
  {
    id: "course-004",
    image: "/images/cards/course-node-backend.jpg",
    title: "Node.js Backend Development",
    description: "Build scalable backend services with Node.js. Cover Express, RESTful APIs, authentication, database integration, and deployment strategies.",
    tags: ["Node.js", "Express", "Backend", "API"],
    categories: ["Programming", "Backend Development"],
    level: "Intermediate",
    relatedQuizzes: 7,
    visibilityStatus: "Public",
    courseCode: "NODE-202-2024",
    enrolledStudents: 649,
    duration: "9 weeks"
  },
  {
    id: "course-005",
    image: "/images/cards/course-next-fullstack.jpg",
    title: "Full-Stack Development with Next.js",
    description: "Learn to build full-stack applications using Next.js. Topics include server components, API routes, authentication, database integration, and deployment strategies.",
    tags: ["Next.js", "React", "Full-Stack", "SSR"],
    categories: ["Programming", "Full-Stack Development"],
    level: "Intermediate",
    relatedQuizzes: 5,
    visibilityStatus: "Public",
    courseCode: "NEXT-205-2024",
    enrolledStudents: 521,
    duration: "12 weeks"
  },
  {
    id: "course-006",
    image: "/images/cards/course-ui-design.jpg",
    title: "UI/UX Design Principles",
    description: "Learn fundamental design principles and how to implement them in your web applications. Covers color theory, typography, layout, accessibility, and user experience design.",
    tags: ["UI", "UX", "Design", "Accessibility"],
    categories: ["Design", "Web Development"],
    level: "Beginner",
    relatedQuizzes: 4,
    visibilityStatus: "Public",
    courseCode: "DESIGN-102-2024",
    enrolledStudents: 876,
    duration: "7 weeks"
  },
  {
    id: "course-007",
    image: "/images/cards/course-data-structures.jpg",
    title: "Data Structures and Algorithms",
    description: "Deep dive into core computer science concepts. Learn arrays, linked lists, trees, graphs, searching, sorting algorithms, and algorithmic complexity analysis.",
    tags: ["DSA", "Algorithms", "Computer Science", "Interview Prep"],
    categories: ["Programming", "Computer Science"],
    level: "Advanced",
    relatedQuizzes: 10,
    visibilityStatus: "Public",
    courseCode: "DSA-301-2024",
    enrolledStudents: 492,
    duration: "14 weeks"
  },
  {
    id: "course-008",
    image: "/images/cards/course-devops.jpg",
    title: "DevOps and CI/CD Practices",
    description: "Learn modern DevOps practices including containerization, orchestration, continuous integration, and deployment. Hands-on with Docker, Kubernetes, and CI/CD pipelines.",
    tags: ["DevOps", "Docker", "Kubernetes", "CI/CD"],
    categories: ["DevOps", "Cloud Computing"],
    level: "Advanced",
    relatedQuizzes: 6,
    visibilityStatus: "Public",
    courseCode: "DEVOPS-305-2024",
    enrolledStudents: 341,
    duration: "10 weeks"
  },
  {
    id: "course-009",
    image: "/images/cards/course-testing.jpg",
    title: "Testing Strategies for Modern Apps",
    description: "Comprehensive guide to testing web applications including unit, integration, and end-to-end testing. Learn Jest, React Testing Library, and Cypress in practical scenarios.",
    tags: ["Testing", "Jest", "Cypress", "TDD"],
    categories: ["Programming", "Quality Assurance"],
    level: "Intermediate",
    relatedQuizzes: 7,
    visibilityStatus: "Public",
    courseCode: "TEST-204-2024",
    enrolledStudents: 413,
    duration: "6 weeks"
  },
  {
    id: "course-010",
    image: "/images/cards/course-graphql.jpg",
    title: "GraphQL API Development",
    description: "Master GraphQL for building flexible and efficient APIs. Learn schema definition, resolvers, queries, mutations, and integration with various frontend and backend technologies.",
    tags: ["GraphQL", "API", "Apollo", "Backend"],
    categories: ["Programming", "API Development"],
    level: "Intermediate",
    relatedQuizzes: 5,
    visibilityStatus: "Public",
    courseCode: "GRAPHQL-203-2024",
    enrolledStudents: 298,
    duration: "8 weeks"
  },
  {
    id: "course-011",
    image: "/images/cards/course-mobile-react-native.jpg",
    title: "React Native Mobile App Development",
    description: "Build cross-platform mobile apps using React Native. Learn components, navigation, state management, and native device features integration.",
    tags: ["React Native", "Mobile", "Cross-Platform", "iOS", "Android"],
    categories: ["Programming", "Mobile Development"],
    level: "Intermediate",
    relatedQuizzes: 6,
    visibilityStatus: "Private",
    courseCode: "RNATIVE-207-2024",
    enrolledStudents: 382,
    duration: "10 weeks"
  },
  {
    id: "course-012",
    image: "/images/cards/course-python.jpg",
    title: "Python for Backend Development",
    description: "Comprehensive guide to building backend services with Python. Covers Flask, Django, RESTful APIs, database integration, and deployment.",
    tags: ["Python", "Django", "Flask", "Backend"],
    categories: ["Programming", "Backend Development"],
    level: "Beginner",
    relatedQuizzes: 8,
    visibilityStatus: "Draft",
    courseCode: "PYTHON-103-2024",
    enrolledStudents: 127,
    duration: "12 weeks"
  }
];