import { TrainingType } from "@/types/TrainingTypes";

export const db: TrainingType[] = [
  {
    id: "1",
    title: "Introduction to React Fundamentals",
    description: "Learn the basics of React including components, props, and state management.",
    stepName: "Frontend Development",
    type: "online-training",
    duration: "2 hours",
    date: "2024-01-15",
    // participants: 10,
    // maxParticipants: 20,
    level: "Beginner",
    startDate: "2024-01-15",
    endDate: "2024-01-22",
    onlineCourse: "https://react-course.example.com"
  },
  {
    id: "2",
    title: "Advanced TypeScript Patterns",
    description: "Deep dive into TypeScript advanced types, generics, and design patterns.",
    stepName: "Programming Languages",
    type: "online-session",
    duration: "3 hours",
    date: "2024-01-18",
    // participants: 12,
    // maxParticipants: 15,
    level: "Advanced",
    startTime: "10:00 AM",
    endTime: "1:00 PM",
    trainerName: "Alex Johnson",
    trainerEmail: "alex@example.com"
  },
  {
    id: "3",
    title: "Database Design Workshop",
    description: "Hands-on workshop covering database normalization, indexing, and optimization.",
    stepName: "Backend Development",
    type: "traditional-session",
    duration: "4 hours",
    date: "2024-01-20",
    // participants: 8,
    // maxParticipants: 12,
    level: "Intermediate",
    startTime: "9:00 AM",
    endTime: "1:00 PM",
    trainerName: "Maria Garcia",
    trainerEmail: "maria@example.com",
    locationAddress: "Tech Hub, 123 Main St",
    locationMapLink: "https://maps.example.com/techhub"
  },
  {
    id: "4",
    title: "API Development with Node.js",
    description: "Build RESTful APIs using Node.js, Express, and MongoDB.",
    stepName: "Backend Development",
    type: "online-training",
    duration: "2.5 hours",
    date: "2024-01-22",
    // participants: 10,
    // maxParticipants: 30,
    level: "Intermediate",
    startDate: "2024-01-22",
    endDate: "2024-01-29",
    onlineCourse: "https://node-api-course.example.com"
  },
  {
    id: "5",
    title: "UI/UX Design Principles",
    description: "Learn fundamental design principles and user experience best practices.",
    stepName: "Design",
    type: "online-session",
    duration: "3 hours",
    date: "2024-01-25",
    // participants: 15,
    // maxParticipants: 20,
    level: "Beginner",
    startTime: "2:00 PM",
    endTime: "5:00 PM",
    trainerName: "David Williams",
    trainerEmail: "david@example.com"
  },
  {
    id: "6",
    title: "DevOps and Deployment Strategies",
    description: "Master CI/CD pipelines, containerization, and cloud deployment.",
    stepName: "DevOps",
    type: "traditional-session",
    duration: "5 hours",
    date: "2024-01-28",
    // participants: 6,
    // maxParticipants: 8,
    level: "Advanced",
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    trainerName: "Sophia Chen",
    trainerEmail: "sophia@example.com",
    locationAddress: "Cloud Center, 456 Tech Blvd",
    locationMapLink: "https://maps.example.com/cloudcenter"
  },
];